br_rod:
# properties:
#   insertion_type: xyz
#   overlap: false
# rod:
#   - length: 20.0
#     x: [0.0, 0.0, 0.0]
#     u: [0.866, 0.5, 0.0]
#   - length: 20.0
#     x: [0.0, 1.5, 0.0]
#     u: [-0.85, -0.5, 0.0]
  properties:
    insertion_type: random
    overlap: false
  rod:
    num: 100
    length: 20
    diameter: 1

xlink:
# properties:
#   insertion_type: xyz
#   overlap: true
# xit:
#   - diameter: 1.0
#     x: [0.0, 0.0, 0.0]
  properties:
    insertion_type: random
    overlap: true
  xit:
    num: 200
    diameter: 1
