br_rod:
  properties:
    insertion_type: xyz
  rod:
    - length: 20.0
      x: [0.0, 0.0, 0.0]
      u: [0.866, 0.5, 0.0]
    - length: 20.0
      x: [0.0, 1.5, 0.0]
      u: [-0.85, -0.5, 0.0]

xlink:
  properties:
    insertion_type: xyz
  xit:
    - diameter: 1.0
      x: [0.0, 0.0, 0.0]
