dy_rod:
  properties:
    insertion_type: random
    overlap: false
    color: [1.0, 0.0, 0.0, 1.0]
  rod:
    num: 600
    length: 15
    min_length: 15
    max_length: 100
    diameter: 1
  #properties:
    #insertion_type: random
    #overlap: true
    #max_length: 10
    #min_length: 10
    #draw_type: orientation
  #rod:
    #num: 50
