filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 10
    length: 30
    persistence_length: 30
    max_length: 100
    min_length: 1
    max_child_length: 2
    diameter: 1

