filament:
  properties:
    insertion_type: random
    overlap: false
  fil:
    num: 80
    length: 20
    persistence_length: 200
    max_length: 100
    min_length: 1
    max_child_length: 3
    diameter: 1

