filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 50
    length: 10
    persistence_length: 10000
    max_length: 100
    min_length: 1.0
    max_child_length: 1.5
    diameter: 1

