filament:
  properties:
    insertion_type: random
    overlap: false
  fil:
    num: 50
    length: 50
    persistence_length: 50
    max_length: 200
    min_length: 1
    max_child_length: 2
    diameter: 1

