filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 25
    length: 40
    persistence_length: 40000
    max_length: 100
    min_length: 1
    max_child_length: 4
    diameter: 1

