filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 50
    length: 20
    persistence_length: 20
    max_length: 100
    min_length: 1
    max_child_length: 4
    diameter: 1

