filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 25
    length: 80
    persistence_length: 80000
    max_length: 100
    min_length: 1
    max_child_length: 7
    diameter: 1

