filament:
  properties:
    insertion_type: random
    overlap: false
  fil:
    num: 100
    length: 20
    persistence_length: 1000
    max_length: 20
    min_length: 1
    max_child_length: 3
    diameter: 1

