filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 20
    length: 100
    persistence_length: 100000
    max_length: 100
    min_length: 1
    max_child_length: 4
    diameter: 1

