filament:
  properties:
    insertion_type: random
    overlap: false
  fil:
    num: 120
    length: 100
    persistence_length: 5000
    max_length: 200
    min_length: 1
    max_child_length: 3
    diameter: 1

