filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 1
    length: 8
    persistence_length: 0
    max_length: 100
    min_length: 1.5
    max_child_length: 1.0
    diameter: 1
