br_rod:
#  properties:
#    insertion_type: random
#    overlap: false
#    color: [1.0, 0.0, 0.0, 1.0]
#    draw_type: flat
#  rod:
#    num: 10
#    length: 10
#    max_length: 10
#    diameter: 1
  properties:
    insertion_type: xyz
    overlap: false
    max_length: 50
    min_length: 3
    draw_type: orientation
  rod:
    - length: 20.0
      x: [0.0, 0.0, 0.0]
      u: [1.0, 0.0, 0.0]
    - length: 20.0
      x: [0.0, 1.5, 0.0]
      u: [-1.0, 0.0, 0.0]
