br_rod:
  properties:
    insertion_type: random
    overlap: true
    color: [1.0, 0.0, 0.0, 1.0]
    draw_type: flat
  rod:
    num: 50
    length: 100
    min_length: 10
    max_length: 100
    diameter: 1
  #properties:
    #insertion_type: random
    #overlap: true
    #max_length: 10
    #min_length: 10
    #draw_type: orientation
  #rod:
    #num: 50
