configuration_type: spindle

spb:
  - properties:
      insertion_type: rtp
      theta: 3.1415926535
      phi: 0.0
      diameter: 9.5
      attach_diameter: 6.5
      diffuse: true
      invisible: true
      draw_type: fill
      color: [1.0, 1.0, 0.0, 1.0]
      mt_max_length: 300.0
      mt_min_length: 2.0
      mt_diameter: 1.0
      r0: 2.0
    mt:
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0

  - properties:
      insertion_type: rtp
      #theta: 0.177
      theta: 2.9645926535
      phi: 1.57
      diameter: 9.5
      attach_diameter: 6.5
      diffuse: true
      invisible: true
      draw_type: fill
      color: [1.0, 1.0, 0.0, 1.0]
      mt_max_length: 300.0
      mt_min_length: 2.0
      mt_diameter: 1.0
      r0: 2.0
    mt:
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0
      - insertion_type: random
        length: 3.0

xlink:
  properties:
    insertion_type: random
    overlap: true
    draw_type: fill
    color: [1.0, 0.0, 0.0, 1.0]
  xit:
    num: 500
    diameter: 1
