#md_bead:
  #properties:
    #insertion_type: random
    #overlap: false
    #TODO Temp
  #mdbead:
    #num: 100
    #diameter: 1
    #mass: 1
    
#br_bead:
  #properties:
    #insertion_type: random
    #overlap: false
    #fill_type: nematic, #polar, isotropic, TODO crystal, smectic
  #brbead:
    #num: 50
    #diameter: 1

br_rod:
  properties:
    insertion_type: fill
    overlap: false
    fill_type: nematic # isotropic, TODO crystal, smectic, polar
    director: [1,0]  # need director for nematic stuff
  rod:
    num: 120
    length: 20
    max_length: 21
    diameter: 1

#xlink:
  #properties:
    #insertion_type: random
    #overlap: true
  #xit:
    #num: 100
    #diameter: 1

#filament:
  #properties:
    #insertion_type: random
    #overlap: true
  #fil:
    #num: 1
    #length: 8
    #persistence_length: 0
    #max_length: 110
    #min_length: 1.5
    #max_child_length: 1.0
    #diameter: 1
