# params.yaml
---
seed: 79741
n_runs: 1
n_dim: 2
n_periodic: 0
system_radius: 40
boundary_type: 1
config_file: params/test_species_config.config.yaml
potfile: params/test_species_config.pot.yaml
kmcfile: params/test_species_config.kmc.yaml
datafile: params/test_species_config.dat.yaml
graph_flag: 1
n_graph: 100
grab_flag: 1
grab_file: frames/frame
graph_background: 0
delta: 0.00001
n_steps: 10000
posit_flag: 1
n_posit: 100
time_flag: 1
energy_analysis_flag: 1
ftype: 4
#masterskin: 1.5
#cell_length: 10
dynamic_instability_flag: 1
