---
language: cpp

services:
  - docker

before_script:
  - docker build -f docker/Dockerfile_base -t jeffmm/simcore_base docker

# Tests are handled during Docker image build
script:
  - docker run --rm -it -v ${PWD}:/build jeffmm/simcore_base:latest bash -c "./install.sh -otI && simcore.exe --version"
...
