seed: 293881442930153

run_name: spindle_test
n_dim: 3
n_periodic: 0
delta: 0.00001
n_steps: 1000000
boundary: 2

graph_flag: true
n_graph: 100
movie_flag: false

system_radius: 30
potential: soft
soft_potential_mag: 1000
f_cutoff: 100000
thermo_flag: true
n_thermo: 100
like_like_interactions: false

checkpoint_flag: true
n_checkpoint: 1000

spindle:
  - name: species
    num: 1
    n_filaments_mother: 3
    n_filaments_bud: 3
    insertion_type: random
    length: 10
    diameter: 10
    spb_diameter: 5
    k_spring: 500

filament:
  - name: spindle
    num: 0
    packing_fraction: -1
    insertion_type: random
    insert_file: params/assay_3d_insert.yaml
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: false
    length: 4
    min_length: 4
    max_length: 120
    min_bond_length: 2
    polydispersity_flag: false
    dynamic_instability_flag: true
    persistence_length: 10000
    driving_factor: 0
    v_poly: 30
    v_depoly: 50
    f_grow_to_shrink: 5
    f_shrink_to_grow: 20
    spec_flag: true
    n_spec: 100
    force_induced_catastrophe_flag: true
    fic_factor: 0.01
crosslink:
  - name: dynein
    concentration: 0.1
    insertion_type: random_boundary
    diameter: 0.3
    walker_flag: true
    velocity: 50
    diffusion_flag: true
    draw_type: fixed
    color: 4.67
    k_on: 50
    k_off: 5
    k_on_d: 100
    k_off_d: 0.001
    force_dep_factor: 0
    polar_affinity: 0
    k_spring: 500
    f_stall: 100
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 1
    step_direction: -1
    tether_draw_type: fixed
    tether_diameter: 0.1
    tether_color: 4.67
    end_pausing: false
    r_capture: 10
    spec_flag: true
    n_spec: 100
  - name: kinesin
    concentration: 0
    insertion_type: random_grid
    diameter: 0.5
    walker_flag: false
    velocity: 100
    diffusion_flag: false
    draw_type: fixed
    color: 0.5
    k_on: 50
    k_off: 5
    k_on_d: 50
    k_off_d: 0.1
    force_dep_factor: 0.001
    polar_affinity: 0
    k_spring: 500
    f_stall: 100
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 0
    step_direction: -1
    tether_draw_type: fixed
    tether_diameter: 0.1
    tether_color: 0.5
    end_pausing: false
    r_capture: 10
    spec_flag: true
    n_spec: 100
