seed: 11782311791392

run_name: wall_bc
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 1000000
boundary: 4

graph_flag: true
n_graph: 1000
movie_flag: false
insert_radius: 900

system_radius: 1000
potential: wca
soft_potential_mag: 1000
f_cutoff: 100000
thermo_flag: false
n_thermo: 100
like_like_interactions: false
interaction_flag: false
checkpoint_flag: false
n_checkpoint: 10000

filament:
  - name: generic
    num: 1
    packing_fraction: 0.01
    insertion_type: random
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: true
    length: 50
    min_bond_length: 3
    peclet_number: 100000
    polydispersity_flag: false
    perlen_ratio: 100
    spec_flag: true
    n_spec: 1000
    n_equil: 0
