# params.yaml
---
seed: 329158164
n_runs: 2
n_dim: 2
n_periodic: 2
system_radius: 20
daughter_radius: 5
mother_daughter_dist: 22
boundary_type: 1
n_dimer: 0
n_md_bead: 0
md_bead_diameter: 0.8
md_bead_mass: 1
n_br_bead: 100
br_bead_diameter: 1.2
dimer_diameter: 1
dimer_length: 2
dimer_eq_length: 2
dimer_k_spring: 5
cell_length: 40
graph_flag: 1
n_graph: 1000
delta: 0.00001
n_steps: 10000
n_update_cells: 10
time_flag: 1
#[brownian_dimer]:
    #num: [2,4]
    #length: 5
    #k_dimer: 10
    #bead_mass: [1,4,8]
#[microtubule]:
    #num: 10
    #persistence_length: 10000
    #dynamic_instability: true
...
