# params.yam
---
seed: 143589714364
n_runs: 1
n_dim: 3
n_periodic: 3
system_radius: 10
daughter_radius: 20
mother_daughter_dist: 22
boundary_type: 1
n_dimer: 0
n_md_bead: 0
md_bead_diameter: 1
md_bead_mass: 1
n_br_bead: 40
br_bead_diameter: 1.2
dimer_diameter: 1
dimer_length: 2
dimer_eq_length: 2
dimer_k_spring: 5
#cell_length: [1.25,2,5]
cell_length: 2.5
graph_flag: 1
n_graph: 200
graph_background: 1
delta: 0.0001
#delta: 0.00001
n_steps: 1000000
n_update_cells: 20
time_flag: 1
energy_analysis_flag: 1
lj_epsilon: 1
n_neon: 0
n_argon: 0
grab_flag: 0
grab_file: frames/frame
#[brownian_dimer]:
    #num: [2,4]
    #length: 5
    #k_dimer: 10
    #bead_mass: [1,4,8]
#[microtubule]:
    #num: 10
    #persistence_length: 10000
    #dynamic_instability: true
...
