seed: 27343246018894

run_name: filament_test
n_dim: 3
n_periodic: 3
delta: 0.0001
n_steps: 20000
n_steps_target: 0
boundary: 0
n_update_cells: 50
cell_length: 5

graph_flag: 1
n_graph: 10
graph_background: 0
movie_flag: 0

system_radius: 150
potential: soft
soft_potential_mag: 10
stoch_flag: 1
f_cutoff: 10000
n_thermo: 100
thermo_flag: 1
interaction_flag: 0

filament:
  num: 100
  packing_fraction: -1
  insertion_type: random
  diameter: 1
  overlap: 1
  length: 50
  perlen_ratio: 1000
  n_bonds: 10
  driving_factor: 0
  n_spec: 100
  n_checkpoint: 100
  spec_flag: 1
  checkpoint_flag: 1
  theta_analysis: 1
  lp_analysis: 1
  posit_flag: 1
  n_posit: 200

