seed: 228312295723876

run_name: anchor_ds
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 10000
n_steps_target: 0
boundary: 0
n_update_cells: 50
cell_length: 6

graph_flag: 1
n_graph: 100
graph_background: 0
movie_flag: 0

system_radius: 100
potential: soft
soft_potential_mag: 300
stoch_flag: 1
f_cutoff: 100000
thermo_flag: 0
n_thermo: 100
interaction_flag: 1

br_bead:
  num: 0
  insertion_type: custom
  insert_file: br_bead_insert.yaml
  draw_type: orientation
  color: 3.14

filament:
  num: 100
  packing_fraction: -1
  insertion_type: random
  #insert_file: anchor_ds_insert.yaml
  diameter: 1
  overlap: 0
  length: 50
  persistence_length: 5000
  perlen_ratio: 200
  n_bonds: 6
  driving_factor: 0
  dynamic_instability_flag: 1
  min_bond_length: 3
  max_bond_length: 6
  polydispersity_flag: 1
  polydispersity_factor: 0.1
  polydispersity_warn_on_truncate: 0
  v_poly: 10
  v_depoly: 20
  f_grow_to_shrink: 100
  f_grow_to_pause: 0
  f_pause_to_shrink: 0
  f_pause_to_grow: 0
  f_shrink_to_pause: 0
  f_shrink_to_grow: 200
  spec_flag: 1
  n_spec: 100
  checkpoint_flag: 1
  n_checkpoint: 100

crosslink:
  concentration: 0.1
  diameter: 1
  walker: 1
  velocity: 10
  diffusion_flag: 1
  draw_type: bw
  color: 0
  k_on: 20
  k_off: 5
  k_on_d: 20
  k_off_d: 5
  force_dep_factor: 0
  polar_affinity: 0
  k_spring: 15
  f_spring_max: 100000
  f_stall: 1000
  force_dep_vel_flag: 1
  k_align: 0
  rest_length: 5
  step_direction: 1
  tether_draw_type: orientation
  tether_diameter: 0.3
  tether_color: 3.1416
  end_pausing: 1
  r_capture: 10
  spec_flag: 1
  n_spec: 100
  checkpoint_flag: 1
  n_checkpoint: 100

