seed: 6809323516356

run_name: fjj
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 100000
boundary: 0
n_update_cells: -1
cell_length: 5

graph_flag: 1
n_graph: 100
graph_background: 0
print_complete: 0

system_radius: 100
potential: soft
soft_potential_mag: 60
#like_like_interactions: 1
stoch_flag: 0
f_cutoff: 500
n_thermo: 100
thermo_flag: 1
local_order_analysis: 0
local_order_bin_width: 0.5
local_order_width: 40
local_order_average: 1
interaction_flag: 1
overlap_analysis: 1

filament:
  num: 2
  packing_fraction: -1
  overlap: 1
  insertion_type: random
  diameter: 1
  length: 50
  perlen_ratio: 20
  n_bonds: 10
  posit_flag: 0
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 10
  n_spec: 10
  n_checkpoint: 100
  driving_factor: 30
  lp_analysis: 1
  global_order_analysis: 0

#passive_filament:
  #num: 0
  #diameter: 1
  #length: 115
  #draw_type: bw
  #insertion_type: custom
  #insert_file: filament_crossing_2.yaml
  #perlen_ratio: 100 
  #n_bonds: 18
  #posit_flag: 1
  #spec_flag: 1
  #checkpoint_flag: 1
  #n_posit: 100
  #n_spec: 100
  #n_checkpoint: 100


