# params.yaml
---
seed : 183873155131077
run_name: lp_driving_1
n_runs: 1
n_random: 1
n_dim: 3
n_periodic: 3
delta: 0.0001
n_steps: 2000000
system_radius: 200
graph_flag: 0
n_graph: 100
movie_flag: 0
movie_directory: frames
cell_length: 10
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 0
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
filament:
  color: 6
  draw_type: orientation
  insertion_type: random
  num: 100
  overlap: 1
  diameter: 1
  spiral_flag: 0
  max_child_length: 3
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 20
  length: 40
  persistence_length: 400
  theta_analysis: 0
  lp_analysis: 1

