# params.yaml
---
seed : 312892776722868
run_name: test
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 0
boundary: 2
delta: 0.0001
n_steps: 100000
n_steps_equil: 0
system_radius: 100
bud_radius: 50
bud_height: 125
graph_flag: 1
n_graph: 100
movie_flag: 0
movie_directory: frames
cell_length: 3
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 0
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
draw_boundary: 1
graph_background: 1
species_insertion_failure_threshold: 10000
uniform_crystal: 0
filament:
  color: 6
  draw_type: bw
  insertion_type: random
  num: 100
  overlap: 1
  diameter: 1
  spiral_flag: 0
  length: -1
  max_length: 100
  min_length: 20
  max_bond_length: 3
  min_bond_length: 1.5
  posit_flag: 0
  spec_flag: 0
  checkpoint_flag: 0
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 10
  persistence_length: 100
  theta_analysis: 0
  lp_analysis: 0

