# params.yaml
---
run_name: sphero_diffusion_test
seed: 298212689221
n_runs: 1

# time options
delta: 0.0001
n_steps: 10000000
n_steps_equil: 0

# space options
n_dim: 3
n_periodic: 0
boundary: 3

# interaction options
interaction_flag: 1
stoch_flag: 1
cell_length: -1
n_update_cells: -1
f_cutoff: 1500

# graphics options
graph_flag: 1
n_graph: 10000
draw_boundary: 1
graph_background: 1
movie_flag: 1
movie_directory: frames

# output options
thermo_flag: 0
n_thermo: 100
species:
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 10000

# model options
append_file: add_spindle.yaml

