seed: 27803201189123

run_name: overhaul_test
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 10000
n_steps_target: 0
boundary: 0
n_update_cells: 50

graph_flag: true
n_graph: 100
movie_flag: false

system_radius: 100
potential: soft
soft_potential_mag: 100
f_cutoff: 10000
thermo_flag: true
n_thermo: 100

checkpoint_flag: true
n_checkpoint: 1000

filament:
  - name: microtubule
    num: 2
    packing_fraction: -1
    insertion_type: random
    diameter: 1
    overlap: false
    length: 50
    min_length: 5
    max_length: 500
    min_bond_length: 3
    polydispersity_flag: true
    dynamic_instability_flag: true
    persistence_length: 5000
    driving_factor: 0
    v_poly: 50
    v_depoly: 50
    f_grow_to_shrink: 10
    f_shrink_to_grow: 20
    spec_flag: true
    n_spec: 100
  - name: actin
    num: 2
    packing_fraction: -1
    insertion_type: random
    diameter: 1
    overlap: false
    length: 50
    min_length: 5
    max_length: 100
    min_bond_length: 3
    polydispersity_flag: true
    dynamic_instability_flag: true
    persistence_length: 200
    driving_factor: 0
    v_poly: 50
    v_depoly: 50
    f_grow_to_shrink: 10
    f_shrink_to_grow: 20
    spec_flag: true
    n_spec: 100

crosslink:
  - name: kinesin
    concentration: 0.05
    diameter: 1.5
    walker_flag: true
    velocity: 50
    diffusion_flag: true
    draw_type: fixed
    color: 4.67
    k_on: 20
    k_off: 5
    k_on_d: 5
    k_off_d: 1
    force_dep_factor: 0
    polar_affinity: 0
    k_spring: 50
    f_stall: 1000
    force_dep_vel_flag: true
    k_align: 0
    rest_length: 1.5
    step_direction: 1
    tether_draw_type: fixed
    tether_diameter: 0.3
    tether_color: 4.67
    end_pausing: false
    r_capture: 10
    spec_flag: true
    n_spec: 100
  - name: ase1
    concentration: 0.05
    diameter: 1
    walker_flag: false
    velocity: 0
    diffusion_flag: true
    draw_type: bw
    color: 0
    k_on: 20
    k_off: 5
    k_on_d: 20
    k_off_d: 5
    force_dep_factor: 0
    polar_affinity: 0
    k_spring: 50
    f_stall: 1000
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 1.5
    step_direction: 1
    tether_draw_type: orientation
    tether_diameter: 0.3
    tether_color: 3.1416
    end_pausing: true
    r_capture: 10
    spec_flag: true
    n_spec: 100
