# params.yaml
---
seed : 19559643324640
run_name: test
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 2
boundary: 0
delta: 0.0003
n_steps: 10000000
n_steps_equil: 0
system_radius: 100
graph_flag: 1
n_graph: 100
movie_flag: 0
movie_directory: frames
cell_length: 3
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 0
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
draw_boundary: 0
graph_background: 1
species_insertion_failure_threshold: 10000
uniform_crystal: 0
filament:
  color: 6
  draw_type: bw
  insertion_type: random
  num: 1
  overlap: 1
  diameter: 1
  spiral_flag: 0
  max_bond_length: 2
  posit_flag: 0
  spec_flag: 0
  checkpoint_flag: 0
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 10
  length: 50
  persistence_length: 500
  theta_analysis: 0
  lp_analysis: 0

