# params.yaml
---
seed : 315932758530486
n_runs: 1
n_dim: 3
n_periodic: 0
delta: 0.00001
n_steps: 50000
system_radius: 100
graph_flag: 1
graph_diameter: 1
n_graph: 1000
cell_length: 200
n_update_cells: 20
diffusion_validation_flag: 1
n_validate: 250
time_flag: 1
tracking_type: 1 # 0 none, 1 ap, 2 mcells, 3 cells, 4 nl ap, 5 nl cells
potfile: params/filament_int.pot.yaml
kmcfile: params/filament_int.kmc.yaml
config_file: params/filament_int.config.yaml
datafile: params/filament_int.dat.yaml
posit_flag: 1
n_posit: 10
avg_posits: 1
diffusion_analysis: 1
diffusion_interval: 300
filament_analysis: 1
#grab_flag: 1
#grab_file: frames/frame

