# params.yaml
---
seed : 13485913453758
n_runs: 1
n_dim: 2
n_periodic: 2
system_radius: 10
daughter_radius: 5
mother_daughter_dist: 0
boundary_type: 1
n_rod: 1
rod_diameter: 1
rod_length: 8
dynamic_instability_flag: 1
force_induced_catastrophe_flag: 1
n_dimer: 0
n_md_bead: 0
md_bead_diameter: 0.2
md_bead_mass: 0.2
n_br_bead: 30
br_bead_diameter: 1
dimer_diameter: 1
dimer_length: 2
dimer_eq_length: 2
dimer_k_spring: 5
max_rod_length: 100
min_rod_length: 1
cell_length: 4
graph_flag: 1
n_graph: 1000
graph_background: 1
delta: 0.00001
n_steps: 5000000
n_update_cells: 20
time_flag: 1
energy_analysis_flag: 1
lj_epsilon: 1
n_neon: 0
n_argon: 0
grab_flag: 0
grab_file: frames/frame
draw_interactions: 0
ftype: 4
v_poly: 0.44
v_depoly: 0.793
potfile: params/hardrods_pot.yaml
#[brownian_dimer]:
    #num: [2,4]
    #length: 5
    #k_dimer: 10
    #bead_mass: [1,4,8]
#[microtubule]:
    #num: 10
    #persistence_length: 10000
    #dynamic_instability: true
...
