# params.yaml
---
run_name: centrosome_test
seed: 47962277021143
n_runs: 1
n_random: 1

# time options
delta: 0.0001
n_steps: 100000000
n_steps_equil: 0

# space options
n_dim: 3
n_periodic: 3
boundary: 3
system_radius: 60
bud_radius: 40
bud_height: 95

# species options
append_file: add_centrosome.yaml

# interaction options
interaction_flag: 1
stoch_flag: 1
cell_length: 5
n_update_cells: 50
f_cutoff: 1000

# graphics options
graph_flag: 1
n_graph: 1000
draw_boundary: 1
graph_background: 1
movie_flag: 0
movie_directory: frames

# output options
thermo_flag: 1
n_thermo: 100
species:
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 10000


