seed: 3290514

run_name: fjf
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 10000
boundary: 0
n_update_cells: -1
cell_length: 5

graph_flag: 1
n_graph: 100
graph_background: 0

system_radius: 200
potential: soft
soft_potential_mag: 100
#like_like_interactions: 1
stoch_flag: 1
f_cutoff: 500
n_thermo: 100
thermo_flag: 1

filament:
  num: 1
  packing_fraction: .004
  overlap: 1
  insertion_type: random_nematic
  diameter: 1
  length: 50
  perlen_ratio: 50
  n_bonds: 18
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 50
  global_order_analysis: 1
  local_order_analysis: 1

#passive_filament:
  #num: 0
  #diameter: 1
  #length: 115
  #draw_type: bw
  #insertion_type: custom
  #insert_file: filament_crossing_2.yaml
  #perlen_ratio: 100 
  #n_bonds: 18
  #posit_flag: 1
  #spec_flag: 1
  #checkpoint_flag: 1
  #n_posit: 100
  #n_spec: 100
  #n_checkpoint: 100


