# params.yaml
---
seed : 190292183726467
n_runs: 1
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 5000
system_radius: 50
graph_flag: 0
graph_diameter: 1
n_graph: 50
cell_length: 3
n_update_cells: 20
diffusion_validation_flag: 0
n_validate: 250
time_flag: 1
driving_factor: 20
tracking_type: 1 # 0 none, 1 ap, 2 mcells, 3 cells, 4 nl ap, 5 nl cells
wca_eps: 1
wca_sig: 1
f_cutoff: 1000
potfile: params/filament_int.pot.yaml
kmcfile: params/filament_int.kmc.yaml
config_file: params/filament_int.config.yaml
datafile: params/filament_int.dat.yaml
posit_flag: 1
n_posit: 10
avg_posits: 1
diffusion_analysis: 1
diffusion_interval: 300
filament_analysis: 1
grab_flag: 0
grab_file: frames/frame

