seed: 2996705641
run_name: activeic_v036
n_dim: 2
n_periodic: 2
delta: 0.00005
n_steps: 10000000
n_steps_equil: 10000
boundary: 0
graph_flag: true
auto_graph: true
n_graph: 10000
movie_flag: false
insert_radius: -1
stoch_flag: true
system_radius: 20
potential: soft
soft_potential_mag: 1000
f_cutoff: 1000000
remove_duplicate_interactions: true
coarse_grained_mesh_interactions: false
mesh_coarsening: 2
thermo_flag: false
n_thermo: 1000
checkpoint_flag: true
n_checkpoint: 10000
species:
  spec_flag: true
  n_spec: 1000
  name: species
  num: 0
  diameter: 1
  length: 0
  insertion_type: random
  insert_file: none
  overlap: false
  draw_type: orientation
  color: 0
  posit_flag: false
  n_posit: 100
filament:
  - name: mt
    num: 30
    packing_fraction: -1
    insertion_type: random_nematic
    draw_type: orientation
    color: 2
    diameter: 1
    overlap: false
    length: 10
    min_length: 6
    max_length: 20
    min_bond_length: 1.2
    polydispersity_flag: false
    persistence_length: 1000
    driving_factor: 10
    n_equil: 20000
    nematic_driving: false
    nematic_driving_freq: 50
    error_analysis: false
    spiral_flag: false
    spiral_number_fail_condition: -1
    intrinsic_curvature: 0.15
    intrinsic_curvature_sig: 0.05
    intrinsic_curvature_min: 0.1
    randomize_intrinsic_curvature_handedness: true
    drive_from_bond_center: true
    peclet_number: -1
    flexure_number: -1
    friction_ratio: 2
    dynamic_instability_flag: false
    force_induced_catastrophe_flag: false
    optical_trap_flag: false
    optical_trap_spring: 20
    optical_trap_fixed: false
    cilia_trap_flag: false
    fic_factor: 0.828
    f_shrink_to_grow: 0.017
    f_shrink_to_pause: 0.0
    f_pause_to_grow: 0.0
    f_pause_to_shrink: 0.0
    f_grow_to_pause: 0.0
    f_grow_to_shrink: 0.00554
    v_poly: 0.44
    v_depoly: 0.793
    theta_analysis: false
    lp_analysis: false
    global_order_analysis: false
    perlen_ratio: -1
    orientation_corr_analysis: false
    orientation_corr_n_steps: 1000
    crossing_analysis: false
    flagella_flag: false
    flagella_freq: 1
    flagella_period: 2
    flagella_amplitude: 1
    flocking_analysis: false
    custom_set_tail: false
    reference_frame_flag: false
    number_fluctuation_analysis: false
    number_fluctuation_boxes: 6
    number_fluctuation_centers: 10
n_runs: 1
n_random: 1
rigid_filament:
  max_length: 500
  min_length: 5
  stationary_flag: false
  packing_fraction: -1
  n_equil: 0
br_bead:
  driving_factor: 0
  packing_fraction: -1
spherocylinder:
  diffusion_analysis: false
  n_diffusion_samples: 1
  midstep: false
spindle:
  n_filaments_bud: 0
  n_filaments_mother: 0
  alignment_potential: false
  k_spring: 1000
  k_align: 0
  spring_length: 0
  spb_diameter: 5
crosslink:
  concentration: 0
  use_binding_volume: true
  infinite_reservoir_flag: false
  bind_site_density: 1
  static_flag: false
  diffusion_s: 0
  diffusion_d: 0
  velocity_s: 0
  velocity_d: 0
  k_on_s: 10
  k_off_s: 2
  k_on_d: 10
  k_off_d: 2
  energy_dep_factor: 0
  force_dep_length: 0
  polar_affinity: 1
  k_spring: 10
  k_spring_compress: -1.
  f_stall: 100
  force_dep_vel_flag: true
  k_align: 0
  rest_length: 0
  step_direction: 0
  tether_draw_type: orientation
  tether_diameter: 0.5
  tether_color: 3.1416
  end_pausing: false
  r_capture: 5
  lut_grid_num: 256
i_step: 0
graph_diameter: 0
invert_background: false
draw_boundary: true
load_checkpoint: false
checkpoint_run_name: sc
n_load: 0
movie_directory: frames
time_analysis: false
bud_height: 680
bud_radius: 300
lj_epsilon: 1
wca_eps: 1
wca_sig: 1
ss_a: 1
ss_rs: 1.5
ss_eps: 1
constant_pressure: false
constant_volume: false
target_pressure: 0
target_radius: 100
pressure_time: 100
compressibility: 1
interaction_flag: true
species_insertion_failure_threshold: 10000
species_insertion_reattempt_threshold: 10
uniform_crystal: false
n_steps_target: 100000
static_particle_number: false
checkpoint_from_spec: false
soft_potential_mag_target: -1
like_like_interactions: true
local_order_analysis: false
local_order_width: 50
local_order_bin_width: 0.5
local_order_n_analysis: 100
density_analysis: 0
density_bin_width: 0.1
density_com_only: false
polar_order_analysis: false
polar_order_n_bins: 100
polar_order_contact_cutoff: 3
overlap_analysis: false
highlight_overlaps: false
reduced: false
reload_reduce_switch: false
flock_polar_min: 0.5
flock_contact_min: 0.5
highlight_flock: false
flock_color_ext: 1.57
flock_color_int: 4.71
in_out_flag: false
no_midstep: false
