# params.yaml
---
seed : 12833525124045
run_name: mse2e_test2
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 2
boundary_type: 0
delta: 0.0001
n_steps: 2000000
n_steps_equil: 0
system_radius: 100
graph_flag: 0
n_graph: 500
movie_flag: 0
movie_directory: frames
cell_length: 3
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 1
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
draw_boundary: 0
graph_background: 1
species_insertion_failure_threshold: 10000
uniform_crystal: 0
filament:
  color: 6
  draw_type: blah
  insertion_type: random
  num: 100
  overlap: 1
  diameter: 1
  spiral_flag: 0
  max_child_length: 3
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 0
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 0
  length: 50
  persistence_length: 500
  theta_analysis: 0
  lp_analysis: 1
