seed: 29122929517437

run_name: rng_problem2
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 100000
boundary: 0

graph_flag: true
n_graph: 100
movie_flag: false

system_radius: 10
potential: soft
soft_potential_mag: 500
f_cutoff: 10000
thermo_flag: true
n_thermo: 100

checkpoint_flag: true
n_checkpoint: 1000

filament:
  - name: microtubule
    num: 1
    packing_fraction: -1
    insertion_type: random
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: false
    length: 10
    min_length: 6
    max_length: 120
    min_bond_length: 1
    polydispersity_flag: false
    dynamic_instability_flag: false
    persistence_length: 1000
    driving_factor: 10
    v_poly: 50
    v_depoly: 50
    f_grow_to_shrink: 10
    f_shrink_to_grow: 20
    spec_flag: true
    n_spec: 100

crosslink:
  - name: dynein
    concentration: 0.5
    insertion_type: random_grid
    diameter: 0.3
    walker_flag: true
    velocity: 100
    diffusion_flag: true
    draw_type: fixed
    color: 4.67
    k_on: 50
    k_off: 5
    k_on_d: 50
    k_off_d: 5
    force_dep_factor: 0.05
    polar_affinity: 0
    k_spring: 50
    f_stall: 100
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 1
    step_direction: -1
    tether_draw_type: fixed
    tether_diameter: 0.1
    tether_color: 4.67
    end_pausing: false
    r_capture: 10
    spec_flag: true
    n_spec: 100
  - name: dead
    concentration: 0.005
    insertion_type: centered
    diameter: 0.5
    walker_flag: false
    velocity: 100
    diffusion_flag: true
    draw_type: fixed
    color: 0.5
    k_on: 50
    k_off: 5
    k_on_d: 500
    k_off_d: 0
    force_dep_factor: 0.001
    polar_affinity: 0
    k_spring: 500
    f_stall: 100
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 0
    step_direction: -1
    tether_draw_type: fixed
    tether_diameter: 0.1
    tether_color: 0.5
    end_pausing: false
    r_capture: 10
    spec_flag: true
    n_spec: 100
