seed: 88391573913763

run_name: feature_test4
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 10000000
boundary: 0

graph_flag: false
auto_graph: true
n_graph: 1000
movie_flag: false
insert_radius: -1
stoch_flag: true

system_radius: 600
potential: soft
soft_potential_mag: 200
f_cutoff: 1000000
coarse_grained_mesh_interactions: true
mesh_coarsening: 2
thermo_flag: false
n_thermo: 1000
checkpoint_flag: true
n_checkpoint: 10000
species:
  spec_flag: true
  n_spec: 10000


filament:
  - name: mt
    num: 1
    packing_fraction: 0.1
    insertion_type: random_nematic
    draw_type: orientation
    color: 2
    diameter: 1
    overlap: false
    length: 60
    min_bond_length: 2.5
    polydispersity_flag: false
    persistence_length: 10
    perlen_ratio: 200
    driving_factor: 30
    error_analysis: false
    spiral_flag: false
    spiral_number_fail_condition: -1
    intrinsic_curvature: 0
    drive_from_bond_center: true
