seed: 134262633418933

run_name: parameter_sweep
n_dim: 3
n_periodic: 3
delta: 0.0001
n_steps: 1000000
boundary: 0

graph_flag: true
n_graph: 100
movie_flag: true
insert_radius: 50

system_radius: 300
potential: soft
soft_potential_mag: 1000
f_cutoff: 100000
thermo_flag: true
n_thermo: 100
like_like_interactions: true
interaction_flag: false

checkpoint_flag: true
n_checkpoint: 1000

filament:
  - name: actin
    num: 300
    insertion_type: random_nematic
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: false
    length: 36
    min_bond_length: 2
    polydispersity_flag: true
    persistence_length: 3400
    spec_flag: true
    n_spec: 100
    n_equil: 1000

crosslink:
  - name: filamen
    concentration: 0
    insertion_type: random
    diameter: 1
    walker_flag: false
    velocity: 0
    diffusion_flag: false
    draw_type: fixed
    color: 4.67
    k_on: 50
    k_off: 5
    k_on_d: 50
    k_off_d: 5
    force_dep_factor: 0
    polar_affinity: 0
    k_spring: 50
    f_stall: 100
    force_dep_vel_flag: false
    k_align: 0
    rest_length: 10
    step_direction: -1
    tether_draw_type: fixed
    tether_diameter: 0.1
    tether_color: 4.67
    end_pausing: false
    r_capture: 30
    spec_flag: true
    n_spec: 100
