# params.yaml
---
seed : 21109641522477
run_name: test
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 200000
system_radius: 20
graph_flag: 1
n_graph: 100
movie_flag: 0
movie_directory: frames
cell_length: 3
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 1
n_thermo: 100
filament:
  insertion_type: oriented
  num: 1
  overlap: 0
  diameter: 1
  spiral_flag: 1
  max_child_length: 3
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: [20,22.5,25,27.5,30]
  length: 40
  persistence_length: 400
