seed: 11782311791392

run_name: filament_undulation
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 500000
boundary: 0

graph_flag: false
n_graph: 100
movie_flag: false
insert_radius: 900

system_radius: 100
potential: wca
soft_potential_mag: 1000
f_cutoff: 100000
thermo_flag: false
n_thermo: 100
like_like_interactions: false
interaction_flag: false
checkpoint_flag: false
n_checkpoint: 10000
stoch_flag: true

filament:
  - name: generic
    num: 10
    packing_fraction: -1
    insertion_type: random
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: true
    length: 60
    min_bond_length: 1.5
    driving_factor: [V, 0, 0.3, 3, 30]
    #peclet_number: 100000
    #flexure_number: 1000000
    polydispersity_flag: false
    perlen_ratio: [V, 5, 20]
    spec_flag: true
    n_spec: 100
    #posit_flag: true
    #n_posit: 1000
    n_equil: 0
    error_analysis: true
