# params.yaml
---
seed : 18772849814367
run_name: test
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 2
delta: 0.001
n_steps: 2000000
system_radius: 100
graph_flag: 1
n_graph: 300
movie_flag: 0
movie_directory: frames
cell_length: 3
n_update_cells: 10
f_cutoff: 1000
thermo_flag: 1
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
filament:
  insertion_type: oriented
  num: 100
  overlap: 1
  diameter: 1
  spiral_flag: 0
  max_child_length: 2
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 0
  length: 50
  persistence_length: 1
