# params.yaml
---
seed : 303722426831655 
#seed: 333681025637
run_name: positioning_test_2
n_runs: 1
n_random: 1
n_dim: 2
n_periodic: 2
boundary: 2
delta: 0.000003
n_steps: 10000000
n_steps_equil: 0
system_radius: 100
bud_radius: 50
bud_height: 125
graph_flag: 1
n_graph: 2000
movie_flag: 1
movie_directory: frames
cell_length: 5
n_update_cells: 10
f_cutoff: 100
thermo_flag: 0
n_thermo: 100
stoch_flag: 1
interaction_flag: 0
draw_boundary: 1
graph_background: 1
species_insertion_failure_threshold: 10000
uniform_crystal: 0
centrosome:
  num: 1
  diameter: 20
  k_spring: 10000
  k_align: 10000
  alignment_potential: 1
  fixed_spacing: 1
  insertion_type: centered_oriented
  n_filaments_max: 4
  n_filaments_min: 4
filament:
  color: 6
  draw_type: bw
  insertion_type: random
  num: 0
  n_motors: 100
  overlap: 1
  diameter: 1
  spiral_flag: 0
  length: -1
  max_length: 100
  min_length: 3
  max_bond_length: 3
  min_bond_length: 1.5
  posit_flag: 0
  spec_flag: 0
  checkpoint_flag: 0
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 0.6
  dynamic_instability_flag: 1
  force_induced_catastrophe_flag: 0
  persistence_length: 10000
  theta_analysis: 0
  lp_analysis: 0
  v_poly: 50
  v_depoly: 50
  f_grow_to_shrink: 0.005
  f_shrink_to_grow: 0.05
motor: 
  draw_type: fixed
  color: 1.5
  diameter: 3
  k_on: 2
  k_off: 1.8
  velocity: 60
  walker: 1
  step_direction: 1
  diffusion_flag: 1
  concentration: 0.08
  k_spring: 10000
  f_spring_max: 10000
