seed: 11782311791392

run_name: active_xlinked
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 1000000
boundary: 0

graph_flag: true
n_graph: 1000
movie_flag: false
insert_radius: -1

system_radius: 200
potential: soft
soft_potential_mag: 1000
f_cutoff: 100000
thermo_flag: true
n_thermo: 1000
checkpoint_flag: true
n_checkpoint: 10000
species:
  spec_flag: true
  n_spec: 1000


filament:
  - name: mt
    num: 1
    packing_fraction: 0.05
    insertion_type: random
    draw_type: fixed
    color: 2
    diameter: 1
    overlap: false
    length: 20
    min_bond_length: 2
    polydispersity_flag: true
    persistence_length: 3000
    driving_factor: 3
    error_analysis: true

crosslink:
  - name: passive
    concentration: 0.1
    insertion_type: random
    diameter: 0.5
    diffusion_s: 1
    diffusion_d: 1
    velocity_s: 0
    velocity_d: 0
    draw_type: bw
    color: 4.67
    k_on_s: 50
    k_off_s: 5
    k_on_d: 50
    k_off_d: 5
    force_dep_factor: 0.1
    polar_affinity: 1
    k_spring: 50
    k2_spring: 0
    anisotropic_spring_flag: false
    f_stall: 100
    force_dep_vel_flag: true
    k_align: 0
    rest_length: 5
    step_direction: -1
    tether_draw_type: bw
    tether_diameter: 0.1
    tether_color: 4.67
    end_pausing: false
    r_capture: 30
