
run_name: crossing_test
n_dim: 2
n_periodic: 0
delta: 0.0001
n_steps: 100000
boundary: 0
n_update_cells: -1

graph_flag: 1
n_graph: 100

system_radius: 50
potential: soft
soft_potential_mag: 40
like_like_interactions: 0
stoch_flag: 0

passive_filament:
  num: 1
  diameter: 1
  length: 115
  draw_type: bw
  insertion_type: custom
  insert_file: filament_crossing_25.yaml
  perlen_ratio: 100 
  n_bonds: 18
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100

filament:
  num: 25
  insertion_type: custom
  insert_file: filament_crossing_25.yaml
  diameter: 1
  length: 50
  perlen_ratio: 100 
  n_bonds: 18
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 100
  n_spec: 100
  n_checkpoint: 100
  driving_factor: 10
