# params.yaml
---
seed : 416987467145
n_runs: 1
n_dim: 2
n_periodic: 2
system_radius: 20
daughter_radius: 5
mother_daughter_dist: 0
boundary_type: 1
metric_forces: 1
n_rod: 0
n_filament: 0
rod_diameter: 1
rod_length: 8
rod_diffusion: 1
rod_fixed: 0
theta_validation_flag: 0
diffusion_validation_flag: 1
dynamic_instability_flag: 0
force_induced_catastrophe_flag: 0
n_dimer: 0
n_md_bead: 0
md_bead_diameter: 0.3
md_bead_mass: 0.1
n_br_bead: 0
br_bead_diameter: 1
dimer_diameter: 1
dimer_length: 2
dimer_eq_length: 2
dimer_k_spring: 5
max_rod_length: 100
min_rod_length: 1.5
max_overlap: 100000
cell_length: 2
graph_flag: 1
n_graph: 500
graph_background: 1
delta: 0.0001
n_steps: 50000
n_validate: 250
n_update_cells: 20
time_flag: 1
energy_analysis_flag: 0
lj_epsilon: 1
n_neon: 0
n_argon: 0
grab_flag: 0
grab_file: frames/frame
draw_interactions: 0
ftype: 4
v_poly: 0.44
v_depoly: 0.793
potfile: params/hard_rods.pot.yaml
kmcfile: params/hard_rods.kmc.yaml
config_file: params/hard_rods.config.yaml
persistence_length: 0
#[brownian_dimer]:
    #num: [2,4]
    #length: 5
    #k_dimer: 10
    #bead_mass: [1,4,8]
#[microtubule]:
    #num: 10
    #persistence_length: 10000
    #dynamic_instability: true
...
