# params.yaml
---
seed : 17140302686691
run_name: test
n_runs: 1
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 100000
system_radius: 40
graph_flag: 1
n_graph: 500
movie_flag: 0
movie_directory: frames
cell_length: 5
n_update_cells: 10
f_cutoff: 9000
append_file: filament.yaml
