FROM ubuntu:bionic

WORKDIR /build

RUN apt-get -qq update && apt-get install -qqy --no-install-recommends \
        build-essential \
        ca-certificates \
        vim \
        cmake \
        wget \
        git \
        curl \
        htop \
        pkg-config \
        doxygen \
        libgsl-dev \
        libfftw3-dev \
        libopenmpi-dev &&\
    rm -rf ~/.cache

RUN apt update && apt install -y libboost-all-dev

RUN wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.0.tar.gz &&\
    tar -xzf yaml-cpp-0.6.0.tar.gz &&\
    cd yaml-cpp-yaml-cpp-0.6.0 &&\
    mkdir build && cd build && cmake .. && make -j4  && make install

RUN git clone --recursive --single-branch --branch separation_paper https://github.com/Betterton-Lab/C-GLASS.git &&\
    cd C-GLASS &&\
    ./install.sh -tI

RUN rm -rf /build
WORKDIR /mnt
ENTRYPOINT []
