filament:
  properties:
    insertion_type: random
    overlap: true
  fil:
    num: 100
    length: 10
    persistence_length: 40000
    max_length: 100
    min_length: 1
    max_child_length: 3
    diameter: 1

