br_rod:
  properties:
    insertion_type: random
    overlap: false
    draw_type: orientation
  rod:
    num: 26
    length: 3
    max_length: 200
    min_length: 2
    diameter: 1
#  properties:
#    insertion_type: xyz
#    overlap: false
#    draw_type: orientation
#    max_length: 200
#    min_length: 2
#    diameter: 1
#  rod:
#    - length: 3.0
#      x: [-3.088781603317358, 11.48382679290238, 53.24378076940775]
#      u: [-0.7868880696419265, 0.5579026795929195, -0.263726687990129]

xlink:
  properties:
    insertion_type: random
    overlap: true
    draw_type: fill
    color: [1.0, 0.0, 0.0, 1.0]
  xit:
    num: 184
    diameter: 1
#  properties:
#    insertion_type: xyz
#    overlap: true
#    draw_type: fill
#    color: [1.0, 0.0, 0.0, 1.0]
#  xit:
#    - diameter: 1
#      x: [-4.269113707780248, 12.32068081229176, 52.84819073742256]
